# Generated by Django 3.2 on 2021-07-22 18:17

from django.db import migrations, models
import django.db.models.deletion
import normas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Nombre de Categoria', max_length=200, verbose_name='Nombre de la Categoria')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name_plural': '1.Normas - Categorias',
            },
        ),
        migrations.CreateModel(
            name='Location_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_name', models.CharField(help_text='Nombre Locacion', max_length=200, verbose_name='Locacion')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name_plural': '3.Normas - Locacion',
            },
        ),
        migrations.CreateModel(
            name='Subcategories_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(help_text='Nombre de sub Categoria', max_length=200, verbose_name='sub Categoria')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name_plural': '2.Normas - SubCategoria',
            },
        ),
        migrations.CreateModel(
            name='Master_Normas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma_name', models.CharField(help_text='Nombre Norma', max_length=200, verbose_name='Norma')),
                ('validity_date_start', models.DateField(help_text='Fecha Publicacion', verbose_name='Fecha Publicacion')),
                ('keywords', models.CharField(help_text='Palabras Clave', max_length=200, verbose_name='Registre palabras clave')),
                ('file', models.FileField(help_text='Suba el archivo o base legal', upload_to=normas.models.upload_file, verbose_name='File')),
                ('register_date_time', models.DateTimeField(auto_now_add=True, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('category_name', models.ForeignKey(help_text='registro de Categoria', on_delete=django.db.models.deletion.CASCADE, to='normas.categories_normas', verbose_name='Categoria')),
                ('location_name', models.ForeignKey(help_text='Registro de Locacion', on_delete=django.db.models.deletion.CASCADE, to='normas.location_normas', verbose_name='Locacion')),
                ('subcategory_name', models.ForeignKey(help_text='registro de SubCategoria', on_delete=django.db.models.deletion.CASCADE, to='normas.subcategories_normas', verbose_name='SubCategoria')),
            ],
            options={
                'verbose_name_plural': '4.Registrar Normas',
            },
        ),
    ]
