# Generated by Django 3.2 on 2021-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_normas',
            name='norma_rne',
            field=models.CharField(blank=True, help_text='Nombre RNE', max_length=50, verbose_name='RNE'),
        ),
    ]
