# Generated by Django 3.2 on 2021-08-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_alter_master_normas_norma_rne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_normas',
            name='area_name',
            field=models.ForeignKey(help_text='registro de Tipo de Uso', on_delete=django.db.models.deletion.CASCADE, to='normas.areas_normas', verbose_name='Tipo de Uso'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='category_name',
            field=models.ForeignKey(help_text='registro Sub Tipo de Uso', on_delete=django.db.models.deletion.CASCADE, to='normas.categories_normas', verbose_name='Sub Tipo de Uso'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='keywords',
            field=models.CharField(blank=True, help_text='Palabras Clave', max_length=200, verbose_name='Registre palabras clave'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='norma_name',
            field=models.CharField(help_text='Nombre de Norma', max_length=200, verbose_name='Norma'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='norma_rne',
            field=models.CharField(blank=True, help_text='Nombre RNE - Norma', max_length=50, verbose_name='RNE-Norma'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='subcategory_name',
            field=models.ForeignKey(help_text='registro Tipo de Normativa', on_delete=django.db.models.deletion.CASCADE, to='normas.subcategories_normas', verbose_name='Tipo de Normativa'),
        ),
    ]
