# Generated by Django 3.2 on 2021-08-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments_foro',
            name='themas',
            field=models.PositiveIntegerField(blank=True, help_text='Tema', null=True, verbose_name='Tema'),
        ),
    ]
