# Generated by Django 3.2 on 2021-07-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planame', models.CharField(help_text='Nombre de Plan', max_length=200, verbose_name='Plan')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=40, null=True)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_member',
            },
        ),
    ]
