# Generated by Django 3.2 on 2021-07-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policies_usage',
            options={'verbose_name_plural': 'Preguntas Frecuentes'},
        ),
        migrations.AlterField(
            model_name='policies_usage',
            name='message',
            field=models.TextField(help_text='Respuesta', verbose_name='Respuesta'),
        ),
    ]
