# Generated by Django 3.2 on 2021-07-13 17:46

import apps.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210713_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_normas',
            options={'verbose_name_plural': 'Normas - Categorias'},
        ),
        migrations.AlterModelOptions(
            name='control_payment',
            options={'verbose_name_plural': 'Control de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='location_normas',
            options={'verbose_name_plural': 'Normas - Locacion'},
        ),
        migrations.AlterModelOptions(
            name='master_normas',
            options={'verbose_name_plural': 'Normas - Registro Principal'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Relacion de Miembros'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'Planes de Suscripcion'},
        ),
        migrations.AlterModelOptions(
            name='subcategories_normas',
            options={'verbose_name_plural': 'Normas - SubCategoria'},
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='category_name',
            field=models.CharField(help_text='registro de Categoria', max_length=200, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='file',
            field=models.ImageField(help_text='Suba el archivo o base legal', upload_to=apps.models.upload_signature, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='keywords',
            field=models.CharField(help_text='Palabras Clave', max_length=200, verbose_name='Registre palabras clave'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='location_name',
            field=models.CharField(help_text='Registro de Locacion', max_length=200, verbose_name='Locacion'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='subcategory_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.categories_normas'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='validity_date_finish',
            field=models.DateField(help_text='Fecha Fin', verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='master_normas',
            name='validity_date_start',
            field=models.DateField(help_text='Fecha Inicio', verbose_name='Fecha Inicio'),
        ),
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
    ]
