# Generated by Django 3.2 on 2021-07-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210722_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_payment',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('E', 'VISA'), ('V', 'EFECTIVO')], help_text='Metodo de Pago', max_length=1, verbose_name='Metodo de Pago'),
        ),
    ]
